### ISSUE TITLE
Animated icons not animated in Safari 10.1.2

### ISSUE THREAD

**Issue by smashism** [SAP/macOS-icon-generator#1]
Hey team, thanks for the great utility! I've noticed that for us the uninstall_animanted.png is not animated in Self Service (our current version is 9.97) or Safari 10.1.2 on macOS Sierra 10.12.6. @rtrouton also tested in Safari 10.1.2 on macOS 10.12.6. The files seem to work fine on Firefox and Chrome. The fact that the files don't work as anticipated in Safari may also relate to them not working as expected in Self Service.

**Comment by smashism** [comment]
This has been tested and working again in Safari 11 on 10.13.0 GM.

**Comment by jonathanbaker7** [comment]
The project is released "as-is" so I'm going to close this bug report.
