### ISSUE TITLE
Add Support for Banner Icons

### ISSUE THREAD

**Issue by uurazzle** [SAP/macOS-icon-generator#12]
Hi:

Thanks for developing and sharing the code and application Icons.

One suggestion would be nice having support creating icon banners for installation, uninstall and update, etc. 

I think many times a graphic vs text option like the banner text "Install", "Uninstall" & "Update" is better for quick review & understanding.

The update would be useful using when updating software like Jamf Patch or policies, or via Munki, etc.

Similar to Matthew Warren's [AppIconExtractor](https://github.com/autopkg/haircut-recipes/blob/master/Processors/AppIconExtractor.py) AutoPkg Processor

Here is a blog post about it...
https://www.macblog.org/posts/appiconextractor/

And a presentation for reference: https://stream.lib.utah.edu/index.php?c=details&id=13501

Would be nice to have a default icon banner similar to AppIconExtractor AutoPkg Processor or the ability to customize and create your own setup of banner icons.

**Comment by mthielemann** [comment]
The upcoming Icons version 2.1.0 will allow you to add an overlay image that can be freely placed on top of the install icon. Hope this helps.
