### ISSUE TITLE
Download instructions are not clear

### ISSUE THREAD

**Issue by amytrkpatel** [SAP/macOS-icon-generator#13]
Wiki page says, download icons. Doesn't mention how or from where. The only thing can be downloaded is the codebase zip from github.

**Comment by rtrouton** [comment]
Every version of Icons has an accompanying GitHub Release:

[https://github.com/SAP/macOS-icon-generator/releases/](https://github.com/SAP/macOS-icon-generator/releases/)

Attached to each Release, there’s an `Icons.zip` file containing a copy of that version’s Icons app. The latest Release is available via this link:

[https://github.com/SAP/macOS-icon-generator/releases/latest](https://github.com/SAP/macOS-icon-generator/releases/latest)
